// <auto-generated />
using System;
using ConsoleApp1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ConsoleApp1.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Kyiv"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Charkov"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Odessa"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "StPetersburg"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            Name = "Washington"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            Name = "Los-Angeles"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 3,
                            Name = "New York"
                        });
                });

            modelBuilder.Entity("ConsoleApp1.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "USA"
                        });
                });

            modelBuilder.Entity("ConsoleApp1.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MainId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ValueDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("ValueDecimal")
                        .HasColumnType("numeric");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("integer");

                    b.Property<string>("ValueString")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("MainId");

                    b.ToTable("Details");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Detail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 4,
                            MainId = 1,
                            Name = "Detail-1",
                            ValueDateTime = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDecimal = 10.12m,
                            ValueInt = 12,
                            ValueString = "В лесу родилась ёлочка в лесу она росла"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 4,
                            MainId = 1,
                            Name = "Detail-2",
                            ValueDateTime = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDecimal = 34.56m,
                            ValueInt = 14,
                            ValueString = "Зимой и летом стройная"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 4,
                            MainId = 1,
                            Name = "Detail-3",
                            ValueDateTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDecimal = 78.9m,
                            ValueInt = 16,
                            ValueString = "Зеленая была"
                        });
                });

            modelBuilder.Entity("ConsoleApp1.Main", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main-1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Main-2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Main-3"
                        });
                });

            modelBuilder.Entity("ConsoleApp1.DetailChild", b =>
                {
                    b.HasBaseType("ConsoleApp1.Detail");

                    b.Property<int?>("ValueChildInt")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("DetailChild");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            MainId = 2,
                            Name = "DetailChild-1",
                            ValueDateTime = new DateTime(2020, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDecimal = 11.2m,
                            ValueInt = 18,
                            ValueString = "Крокодилы-бегемоты и зеленый попугай",
                            ValueChildInt = 1
                        });
                });

            modelBuilder.Entity("ConsoleApp1.City", b =>
                {
                    b.HasOne("ConsoleApp1.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.Detail", b =>
                {
                    b.HasOne("ConsoleApp1.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("ConsoleApp1.Main", "Main")
                        .WithMany("Details")
                        .HasForeignKey("MainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
